author: John Fairhurst
author_url: http://github.com/johnfairh
module: RubyGateway
module_version: 6.1.0
copyright: Distributed under the MIT license.  Maintained by [John Fairhurst](mailto:johnfairh@gmail.com).
readme: README.md
github_url: https://github.com/johnfairh/RubyGateway
github_file_prefix: https://github.com/johnfairh/RubyGateway/tree/main
clean: true
products:
  - docs
  - docset
  - unresolved-json
  - undocumented-json
xcodebuild_arguments:
    - "-project"
    - "RubyGateway.xcodeproj"
    - "-scheme"
    - "RubyGateway-Package"
    - "-destination"
    - "platform=OS X,arch=x86_64"
sdk: macosx
theme: fw2020
documentation: SourceDocs/*md
topic_style: source-order-defs
deployment_url: https://johnfairh.github.io/RubyGateway/

custom_categories:
    - name: Guides
      children:
          - User Guide
          - TODO

    - name: Main APIs
      abstract: These types form the main API to RubyGateway.
      children:
          - RbGateway
          - RbObject
          - RbObjectAccess
          - RbObjectCollection

    - name: Swift Method APIs
      abstract: These types are used to implement Ruby methods in Swift.
      children:
          - RbMethodArgsSpec
          - RbMethodCallback
          - RbBoundMethodCallback
          - RbBoundMethodVoidCallback
          - RbMethod
          - RbMethodArgs

    - name: Other APIs
      abstract: These types are used less often than those in [`Main APIs`](Main%20APIs.html).
      children:
          - RbBlockCallback
          - RbBlockRetention
          - RbBreak
          - RbProc
          - RbSymbol
          - RbThread
          - RbType

    - name: Error Handling
      abstract: These types are used to deal with error conditions.
      children:
          - RbError
          - RbException
          - RbFailableAccess

    - name: Swift Interop
      abstract: These types and extensions are used to convert Swift datatypes to Ruby and vice versa.
      children:
          - RbObjectConvertible
          - String
          - Bool
          - UInt
          - UInt64
          - UInt32
          - UInt16
          - UInt8
          - Int
          - Int64
          - Int32
          - Int16
          - Int8
          - Double
          - Float
          - Array
          - ArraySlice
          - Dictionary
          - Set
          - Range
          - ClosedRange
          - RbComplex
          - RbRational
