#! /bin/bash
set -xev
T_CFLAGS=`grep Cflags CRuby/CRuby.pc|sed -e 's/Cflags: //'`
T_LDFLAGS=`grep Libs CRuby/CRuby.pc|sed -e 's/Libs: //'`
xcodebuild clean build test -sdk macosx -project RubyBridge.xcodeproj -scheme RubyBridge-Package CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES VALID_ARCHS=x86_64 OTHER_LDFLAGS="${T_LDFLAGS}" OTHER_CFLAGS="${T_CFLAGS}" -verbose
